services:
  - type: web
    name: vlights-ar
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: vlights-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 3000
      - key: DASHBOARD_PASSWORD
        value: Prakash_9892284364
      - key: DB_PATH
        value: /data/vlights.db
      - key: TELEGRAM_BOT_TOKEN
        value: 8666300315:AAGVUPQNmYMf9iQX_o2giKfQFcnPKxl2uCE
      - key: TELEGRAM_CHAT_ID
        value: 5767644169
